export type SettingType = 'color' | 'number' | 'text' | 'select' | 'boolean';
export type SettingCategory =
  | 'commonly_used'
  | 'ai'
  | 'appearance'
  | 'colors'
  | 'terminal'
  | 'git'
  | 'accounts'
  | 'notifications'
  | 'advanced';

export type SettingScope = 'app' | 'repo';

export interface SettingOption {
  label: string;
  value: string;
}

export interface SettingDefinition {
  id: string;
  label: string;
  description: string;
  category: SettingCategory;
  subcategory: string;
  type: SettingType;
  cssVar?: string;
  options?: SettingOption[];
  default: string | number | boolean;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  scope: SettingScope;
  commonlyUsed?: boolean;
}

export const CATEGORY_METADATA: Record<
  SettingCategory,
  { label: string; icon: string; subcategories: string[] }
> = {
  commonly_used: {
    label: 'Commonly Used',
    icon: 'Star',
    subcategories: ['Featured Settings'],
  },
  ai: {
    label: 'AI & Commit-AI',
    icon: 'Sparkles',
    subcategories: ['API Keys & Providers', 'Model Configuration'],
  },
  appearance: {
    label: 'Appearance',
    icon: 'Palette',
    subcategories: ['Typography', 'Spacing & Shape', 'Elevation & Motion', 'Density'],
  },
  colors: {
    label: 'Colors',
    icon: 'Paintbrush',
    subcategories: [
      'Surfaces',
      'Text',
      'Accent & Status',
      'Git Diff Colors',
      'Provider Badges',
    ],
  },
  terminal: {
    label: 'Terminal',
    icon: 'Terminal',
    subcategories: ['Font & Cursor', 'ANSI Colors', 'App Log Colors'],
  },
  git: {
    label: 'Git',
    icon: 'GitBranch',
    subcategories: ['Repository Defaults', 'Sync & Remote Operations', 'Safety Checks'],
  },
  accounts: {
    label: 'Accounts & Security',
    icon: 'Shield',
    subcategories: ['Authentication & Tokens', 'Log Storage'],
  },
  notifications: {
    label: 'Notifications',
    icon: 'Bell',
    subcategories: ['System Alerts'],
  },
  advanced: {
    label: 'Advanced',
    icon: 'Sliders',
    subcategories: ['Diagnostics & Performance'],
  },
};

export const SETTINGS_SCHEMA: SettingDefinition[] = [
  // ==========================================
  // AI & COMMIT-AI
  // ==========================================
  {
    id: 'ai.active_api_key',
    label: 'Groq API Key',
    description: 'Active Groq API Key (gsk_...) used for AI commit message generation and diff analysis.',
    category: 'ai',
    subcategory: 'API Keys & Providers',
    type: 'text',
    default: '',
    scope: 'app',
    commonlyUsed: true,
  },
  {
    id: 'ai.model',
    label: 'Commit-AI Model',
    description: 'The LLM model used for analyzing diffs and generating commit messages.',
    category: 'ai',
    subcategory: 'Model Configuration',
    type: 'select',
    options: [
      { label: 'OpenAI GPT OSS 120B (Recommended)', value: 'openai/gpt-oss-120b' },
      { label: 'Llama 3.3 70B Versatile', value: 'llama-3.3-70b-versatile' },
      { label: 'Llama 3 70B (8192)', value: 'llama3-70b-8192' },
      { label: 'Mixtral 8x7B (32768)', value: 'mixtral-8x7b-32768' },
    ],
    default: 'openai/gpt-oss-120b',
    scope: 'app',
    commonlyUsed: true,
  },
  {
    id: 'ai.temperature',
    label: 'Sampling Temperature',
    description: 'Controls creativity of the generated commit titles (0.0 to 1.0).',
    category: 'ai',
    subcategory: 'Model Configuration',
    type: 'number',
    min: 0.0,
    max: 1.0,
    step: 0.1,
    default: 0.7,
    scope: 'app',
  },

  // ==========================================
  // COMMONLY USED (Pinned Quick Access)
  // ==========================================
  {
    id: 'appearance.accent',
    label: 'Primary Accent Color',
    description: 'Accent color used across active tabs, primary buttons, commit actions, and badges.',
    category: 'commonly_used',
    subcategory: 'Featured Settings',
    type: 'color',
    cssVar: '--app-accent',
    default: '#e05638',
    scope: 'app',
    commonlyUsed: true,
  },
  {
    id: 'appearance.fontSize',
    label: 'Base Font Size',
    description: 'Base typography size driving text throughout all panels and controls.',
    category: 'commonly_used',
    subcategory: 'Featured Settings',
    type: 'number',
    cssVar: '--app-font-size',
    default: 13,
    min: 11,
    max: 18,
    step: 1,
    unit: 'px',
    scope: 'app',
    commonlyUsed: true,
  },
  {
    id: 'appearance.radiusMd',
    label: 'Border Radius',
    description: 'Corner radius applied to buttons, input fields, cards, and interactive rows.',
    category: 'commonly_used',
    subcategory: 'Featured Settings',
    type: 'number',
    cssVar: '--app-radius-md',
    default: 6,
    min: 0,
    max: 16,
    step: 1,
    unit: 'px',
    scope: 'app',
    commonlyUsed: true,
  },
  {
    id: 'appearance.density',
    label: 'UI Density Mode',
    description: 'Scales spacing, padding, and row heights simultaneously across the entire UI.',
    category: 'commonly_used',
    subcategory: 'Featured Settings',
    type: 'select',
    cssVar: '--app-density',
    options: [
      { label: 'Comfortable (Standard)', value: 'comfortable' },
      { label: 'Compact (Dense)', value: 'compact' },
    ],
    default: 'comfortable',
    scope: 'app',
    commonlyUsed: true,
  },

  // ==========================================
  // APPEARANCE: Typography
  // ==========================================
  {
    id: 'typography.fontFamily',
    label: 'UI Font Family',
    description: 'Font family stack for all application labels, inputs, and dialogs.',
    category: 'appearance',
    subcategory: 'Typography',
    type: 'select',
    cssVar: '--app-font-family',
    options: [
      { label: 'Inter (Default)', value: "Inter, system-ui, -apple-system, sans-serif" },
      { label: 'System UI', value: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" },
      { label: 'Segoe UI (Windows)', value: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" },
      { label: 'Roboto', value: "Roboto, -apple-system, sans-serif" },
    ],
    default: "Inter, system-ui, -apple-system, sans-serif",
    scope: 'app',
  },
  {
    id: 'typography.fontSize',
    label: 'Main Font Size',
    description: 'Default size for body text and standard controls.',
    category: 'appearance',
    subcategory: 'Typography',
    type: 'number',
    cssVar: '--app-font-size',
    default: 13,
    min: 11,
    max: 18,
    step: 1,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'typography.fontSizeSm',
    label: 'Small Font Size',
    description: 'Font size for secondary labels, metadata tags, and timestamps.',
    category: 'appearance',
    subcategory: 'Typography',
    type: 'number',
    cssVar: '--app-font-size-sm',
    default: 11,
    min: 9,
    max: 14,
    step: 1,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'typography.fontSizeLg',
    label: 'Heading Font Size',
    description: 'Font size for primary section headers and title labels.',
    category: 'appearance',
    subcategory: 'Typography',
    type: 'number',
    cssVar: '--app-font-size-lg',
    default: 15,
    min: 13,
    max: 22,
    step: 1,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'typography.lineHeight',
    label: 'Line Height',
    description: 'Relative line-height multiplier for paragraph and multi-line text.',
    category: 'appearance',
    subcategory: 'Typography',
    type: 'number',
    cssVar: '--app-line-height',
    default: 1.5,
    min: 1.1,
    max: 2.0,
    step: 0.05,
    scope: 'app',
  },

  // ==========================================
  // APPEARANCE: Spacing & Shape
  // ==========================================
  {
    id: 'shape.radiusSm',
    label: 'Small Corner Radius',
    description: 'Radius for small chips, badges, and status pills.',
    category: 'appearance',
    subcategory: 'Spacing & Shape',
    type: 'number',
    cssVar: '--app-radius-sm',
    default: 4,
    min: 0,
    max: 10,
    step: 1,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'shape.radiusMd',
    label: 'Standard Corner Radius',
    description: 'Radius for standard buttons, inputs, dropdown menus, and cards.',
    category: 'appearance',
    subcategory: 'Spacing & Shape',
    type: 'number',
    cssVar: '--app-radius-md',
    default: 6,
    min: 0,
    max: 16,
    step: 1,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'shape.radiusLg',
    label: 'Large Modal Corner Radius',
    description: 'Radius for floating dialogs, modals, and main overlays.',
    category: 'appearance',
    subcategory: 'Spacing & Shape',
    type: 'number',
    cssVar: '--app-radius-lg',
    default: 12,
    min: 0,
    max: 28,
    step: 1,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'shape.spacingUnit',
    label: 'Base Spacing Multiplier',
    description: 'Base unit driving layout padding, gutter margins, and item gaps.',
    category: 'appearance',
    subcategory: 'Spacing & Shape',
    type: 'number',
    cssVar: '--app-spacing-unit',
    default: 4,
    min: 2,
    max: 8,
    step: 1,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'shape.sidebarWidth',
    label: 'Sidebar Width',
    description: 'Default width of the repository and navigation sidebar.',
    category: 'appearance',
    subcategory: 'Spacing & Shape',
    type: 'number',
    cssVar: '--app-sidebar-width',
    default: 260,
    min: 200,
    max: 420,
    step: 10,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'shape.rowHeight',
    label: 'List Row Height',
    description: 'Standard height of file lists, repository items, and history rows.',
    category: 'appearance',
    subcategory: 'Spacing & Shape',
    type: 'number',
    cssVar: '--app-row-height',
    default: 38,
    min: 28,
    max: 56,
    step: 2,
    unit: 'px',
    scope: 'app',
  },

  // ==========================================
  // APPEARANCE: Elevation & Motion
  // ==========================================
  {
    id: 'elevation.shadowSm',
    label: 'Small Elevation Shadow',
    description: 'Drop shadow for elevated dropdown triggers and small floating controls.',
    category: 'appearance',
    subcategory: 'Elevation & Motion',
    type: 'text',
    cssVar: '--app-shadow-sm',
    default: '0 1px 2px 0 rgba(0, 0, 0, 0.25)',
    scope: 'app',
  },
  {
    id: 'elevation.shadowMd',
    label: 'Medium Surface Shadow',
    description: 'Drop shadow for dropdown panels and floating menus.',
    category: 'appearance',
    subcategory: 'Elevation & Motion',
    type: 'text',
    cssVar: '--app-shadow-md',
    default: '0 4px 6px -1px rgba(0, 0, 0, 0.4)',
    scope: 'app',
  },
  {
    id: 'elevation.shadowLg',
    label: 'Large Modal Shadow',
    description: 'Deep drop shadow for main modal dialogs and fullscreen overlays.',
    category: 'appearance',
    subcategory: 'Elevation & Motion',
    type: 'text',
    cssVar: '--app-shadow-lg',
    default: '0 10px 25px -3px rgba(0, 0, 0, 0.6)',
    scope: 'app',
  },
  {
    id: 'motion.transitionFast',
    label: 'Fast Animation Duration',
    description: 'Transition timing for hover states and quick highlights.',
    category: 'appearance',
    subcategory: 'Elevation & Motion',
    type: 'select',
    cssVar: '--app-transition-fast',
    options: [
      { label: '50ms (Snappy)', value: '50ms' },
      { label: '100ms (Default)', value: '100ms' },
      { label: '150ms (Smooth)', value: '150ms' },
    ],
    default: '100ms',
    scope: 'app',
  },
  {
    id: 'motion.transitionNormal',
    label: 'Normal Animation Duration',
    description: 'Transition timing for panel expansions and modal entries.',
    category: 'appearance',
    subcategory: 'Elevation & Motion',
    type: 'select',
    cssVar: '--app-transition-normal',
    options: [
      { label: '150ms (Fast)', value: '150ms' },
      { label: '200ms (Default)', value: '200ms' },
      { label: '300ms (Relaxed)', value: '300ms' },
    ],
    default: '200ms',
    scope: 'app',
  },

  // ==========================================
  // COLORS: Surfaces
  // ==========================================
  {
    id: 'colors.bgPrimary',
    label: 'Main Workspace Background',
    description: 'Primary canvas background for diff viewers, editor views, and main content.',
    category: 'colors',
    subcategory: 'Surfaces',
    type: 'color',
    cssVar: '--app-bg-primary',
    default: '#171619',
    scope: 'app',
  },
  {
    id: 'colors.bgSecondary',
    label: 'Sidebar & Frame Background',
    description: 'Background color for sidebars, top titlebar, and docked panels.',
    category: 'colors',
    subcategory: 'Surfaces',
    type: 'color',
    cssVar: '--app-bg-secondary',
    default: '#121113',
    scope: 'app',
  },
  {
    id: 'colors.bgElevated',
    label: 'Elevated Surface Background',
    description: 'Background color for cards, dropdown menus, and modal dialogs.',
    category: 'colors',
    subcategory: 'Surfaces',
    type: 'color',
    cssVar: '--app-bg-elevated',
    default: '#201e22',
    scope: 'app',
  },
  {
    id: 'colors.surfaceHover',
    label: 'Row Hover Background',
    description: 'Background color shown when hovering over clickable rows and list items.',
    category: 'colors',
    subcategory: 'Surfaces',
    type: 'color',
    cssVar: '--app-surface-hover',
    default: '#2b292f',
    scope: 'app',
  },
  {
    id: 'colors.surfaceActive',
    label: 'Active Item Background',
    description: 'Background color for selected items and active nav rows.',
    category: 'colors',
    subcategory: 'Surfaces',
    type: 'color',
    cssVar: '--app-surface-active',
    default: '#382221',
    scope: 'app',
  },
  {
    id: 'colors.border',
    label: 'Default Border Color',
    description: 'Subtle separator and boundary line color used across all panels.',
    category: 'colors',
    subcategory: 'Surfaces',
    type: 'color',
    cssVar: '--app-border',
    default: '#29272b',
    scope: 'app',
  },
  {
    id: 'colors.borderStrong',
    label: 'Emphasized Border Color',
    description: 'High-contrast border color for focused inputs and active modal outlines.',
    category: 'colors',
    subcategory: 'Surfaces',
    type: 'color',
    cssVar: '--app-border-strong',
    default: '#3d3a42',
    scope: 'app',
  },

  // ==========================================
  // COLORS: Text
  // ==========================================
  {
    id: 'colors.textPrimary',
    label: 'Primary Text Color',
    description: 'Main body, titles, and active label text color.',
    category: 'colors',
    subcategory: 'Text',
    type: 'color',
    cssVar: '--app-text-primary',
    default: '#e6e4e8',
    scope: 'app',
  },
  {
    id: 'colors.textSecondary',
    label: 'Secondary Text Color',
    description: 'Metadata tags, secondary breadcrumbs, and branch names.',
    category: 'colors',
    subcategory: 'Text',
    type: 'color',
    cssVar: '--app-text-secondary',
    default: '#b3b0b8',
    scope: 'app',
  },
  {
    id: 'colors.textMuted',
    label: 'Muted Text Color',
    description: 'Disabled text, placeholder hints, and subtle timestamps.',
    category: 'colors',
    subcategory: 'Text',
    type: 'color',
    cssVar: '--app-text-muted',
    default: '#85818c',
    scope: 'app',
  },
  {
    id: 'colors.textOnAccent',
    label: 'Text On Accent Color',
    description: 'High-contrast text rendered on solid accent backgrounds (Push button, active pills).',
    category: 'colors',
    subcategory: 'Text',
    type: 'color',
    cssVar: '--app-text-on-accent',
    default: '#ffffff',
    scope: 'app',
  },

  // ==========================================
  // COLORS: Accent & Status
  // ==========================================
  {
    id: 'colors.accent',
    label: 'Accent Color',
    description: 'Primary brand accent color for active items, buttons, and highlights.',
    category: 'colors',
    subcategory: 'Accent & Status',
    type: 'color',
    cssVar: '--app-accent',
    default: '#e05638',
    scope: 'app',
  },
  {
    id: 'colors.accentHover',
    label: 'Accent Hover Color',
    description: 'Lighter or more vibrant accent tone shown on hover.',
    category: 'colors',
    subcategory: 'Accent & Status',
    type: 'color',
    cssVar: '--app-accent-hover',
    default: '#f06344',
    scope: 'app',
  },
  {
    id: 'colors.accentMuted',
    label: 'Muted Accent Fill',
    description: 'Low-opacity accent tint used for selected row backgrounds.',
    category: 'colors',
    subcategory: 'Accent & Status',
    type: 'text',
    cssVar: '--app-accent-muted',
    default: 'rgba(224, 86, 56, 0.15)',
    scope: 'app',
  },
  {
    id: 'colors.success',
    label: 'Success Color',
    description: 'Positive status indicator (clean repo, successful sync, valid tokens).',
    category: 'colors',
    subcategory: 'Accent & Status',
    type: 'color',
    cssVar: '--app-success',
    default: '#22c55e',
    scope: 'app',
  },
  {
    id: 'colors.warning',
    label: 'Warning Color',
    description: 'Caution status indicator (ahead/behind counts, expiring tokens).',
    category: 'colors',
    subcategory: 'Accent & Status',
    type: 'color',
    cssVar: '--app-warning',
    default: '#eab308',
    scope: 'app',
  },
  {
    id: 'colors.error',
    label: 'Error Color',
    description: 'Critical alerts, dirty state badges, and failed operations.',
    category: 'colors',
    subcategory: 'Accent & Status',
    type: 'color',
    cssVar: '--app-error',
    default: '#ef4444',
    scope: 'app',
  },
  {
    id: 'colors.info',
    label: 'Information Color',
    description: 'Informational badges, tooltips, and help links.',
    category: 'colors',
    subcategory: 'Accent & Status',
    type: 'color',
    cssVar: '--app-info',
    default: '#3b82f6',
    scope: 'app',
  },

  // ==========================================
  // COLORS: Git Diff Colors
  // ==========================================
  {
    id: 'git.colorAdded',
    label: 'Added Lines / Files',
    description: 'Diff viewer color for added text and newly created files.',
    category: 'colors',
    subcategory: 'Git Diff Colors',
    type: 'color',
    cssVar: '--git-added',
    default: '#22c55e',
    scope: 'app',
  },
  {
    id: 'git.colorRemoved',
    label: 'Removed Lines / Files',
    description: 'Diff viewer color for deleted lines and removed files.',
    category: 'colors',
    subcategory: 'Git Diff Colors',
    type: 'color',
    cssVar: '--git-removed',
    default: '#ef4444',
    scope: 'app',
  },
  {
    id: 'git.colorModified',
    label: 'Modified Files',
    description: 'Status badge and icon color for modified working tree files.',
    category: 'colors',
    subcategory: 'Git Diff Colors',
    type: 'color',
    cssVar: '--git-modified',
    default: '#eab308',
    scope: 'app',
  },
  {
    id: 'git.colorRenamed',
    label: 'Renamed Files',
    description: 'Indicator color for renamed or moved files.',
    category: 'colors',
    subcategory: 'Git Diff Colors',
    type: 'color',
    cssVar: '--git-renamed',
    default: '#3b82f6',
    scope: 'app',
  },
  {
    id: 'git.colorConflict',
    label: 'Merge Conflict Indicator',
    description: 'Indicator color for unresolved merge and rebase conflicts.',
    category: 'colors',
    subcategory: 'Git Diff Colors',
    type: 'color',
    cssVar: '--git-conflict',
    default: '#f97316',
    scope: 'app',
  },
  {
    id: 'git.colorAhead',
    label: 'Commits Ahead Indicator',
    description: 'Indicator badge color for commits ahead of remote (↑).',
    category: 'colors',
    subcategory: 'Git Diff Colors',
    type: 'color',
    cssVar: '--git-ahead',
    default: '#22c55e',
    scope: 'app',
  },
  {
    id: 'git.colorBehind',
    label: 'Commits Behind Indicator',
    description: 'Indicator badge color for commits behind remote (↓).',
    category: 'colors',
    subcategory: 'Git Diff Colors',
    type: 'color',
    cssVar: '--git-behind',
    default: '#ef4444',
    scope: 'app',
  },

  // ==========================================
  // COLORS: Provider Badges
  // ==========================================
  {
    id: 'provider.gitlab',
    label: 'GitLab Provider Color',
    description: 'Icon and badge tint for GitLab accounts and remote repositories.',
    category: 'colors',
    subcategory: 'Provider Badges',
    type: 'color',
    cssVar: '--provider-gitlab',
    default: '#e24329',
    scope: 'app',
  },
  {
    id: 'provider.github',
    label: 'GitHub Provider Color',
    description: 'Icon and badge tint for GitHub accounts and remote repositories.',
    category: 'colors',
    subcategory: 'Provider Badges',
    type: 'color',
    cssVar: '--provider-github',
    default: '#2da44e',
    scope: 'app',
  },

  // ==========================================
  // TERMINAL: Font & Cursor
  // ==========================================
  {
    id: 'terminal.fontFamily',
    label: 'Terminal Monospace Font',
    description: 'Monospace font family for the interactive terminal and log viewer.',
    category: 'terminal',
    subcategory: 'Font & Cursor',
    type: 'select',
    cssVar: '--terminal-font-family',
    options: [
      { label: 'JetBrains Mono', value: "'JetBrains Mono', monospace" },
      { label: 'Fira Code', value: "'Fira Code', monospace" },
      { label: 'Cascadia Code / Consolas', value: "'Cascadia Code', Consolas, monospace" },
      { label: 'Menlo / Monaco', value: 'Menlo, Monaco, monospace' },
    ],
    default: "'JetBrains Mono', 'Fira Code', Menlo, Monaco, Consolas, monospace",
    scope: 'app',
  },
  {
    id: 'terminal.fontSize',
    label: 'Terminal Font Size',
    description: 'Font size for xterm canvas characters and stream log lines.',
    category: 'terminal',
    subcategory: 'Font & Cursor',
    type: 'number',
    cssVar: '--terminal-font-size',
    default: 13,
    min: 10,
    max: 20,
    step: 1,
    unit: 'px',
    scope: 'app',
  },
  {
    id: 'terminal.bg',
    label: 'Terminal Background',
    description: 'Canvas background for interactive terminal sessions.',
    category: 'terminal',
    subcategory: 'Font & Cursor',
    type: 'color',
    cssVar: '--terminal-bg',
    default: '#121113',
    scope: 'app',
  },
  {
    id: 'terminal.fg',
    label: 'Terminal Default Foreground',
    description: 'Default text color for normal command output in terminal.',
    category: 'terminal',
    subcategory: 'Font & Cursor',
    type: 'color',
    cssVar: '--terminal-fg',
    default: '#e6e4e8',
    scope: 'app',
  },
  {
    id: 'terminal.cursor',
    label: 'Terminal Cursor Color',
    description: 'Color of the blinking input prompt cursor.',
    category: 'terminal',
    subcategory: 'Font & Cursor',
    type: 'color',
    cssVar: '--terminal-cursor',
    default: '#e05638',
    scope: 'app',
  },
  {
    id: 'terminal.selection',
    label: 'Terminal Selection Highlight',
    description: 'Highlight color for selected text in terminal output.',
    category: 'terminal',
    subcategory: 'Font & Cursor',
    type: 'color',
    cssVar: '--terminal-selection',
    default: '#382221',
    scope: 'app',
  },

  // ==========================================
  // TERMINAL: ANSI Colors (16 Swatches)
  // ==========================================
  {
    id: 'terminal.ansiBlack',
    label: 'ANSI Black',
    description: 'Standard ANSI Color 0',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-black',
    default: '#171619',
    scope: 'app',
  },
  {
    id: 'terminal.ansiRed',
    label: 'ANSI Red',
    description: 'Standard ANSI Color 1',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-red',
    default: '#f87171',
    scope: 'app',
  },
  {
    id: 'terminal.ansiGreen',
    label: 'ANSI Green',
    description: 'Standard ANSI Color 2',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-green',
    default: '#4ade80',
    scope: 'app',
  },
  {
    id: 'terminal.ansiYellow',
    label: 'ANSI Yellow',
    description: 'Standard ANSI Color 3',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-yellow',
    default: '#facc15',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBlue',
    label: 'ANSI Blue',
    description: 'Standard ANSI Color 4',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-blue',
    default: '#60a5fa',
    scope: 'app',
  },
  {
    id: 'terminal.ansiMagenta',
    label: 'ANSI Magenta',
    description: 'Standard ANSI Color 5',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-magenta',
    default: '#c084fc',
    scope: 'app',
  },
  {
    id: 'terminal.ansiCyan',
    label: 'ANSI Cyan',
    description: 'Standard ANSI Color 6',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-cyan',
    default: '#38bdf8',
    scope: 'app',
  },
  {
    id: 'terminal.ansiWhite',
    label: 'ANSI White',
    description: 'Standard ANSI Color 7',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-white',
    default: '#e6e4e8',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBrightBlack',
    label: 'ANSI Bright Black (Gray)',
    description: 'Bright ANSI Color 8',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-bright-black',
    default: '#85818c',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBrightRed',
    label: 'ANSI Bright Red',
    description: 'Bright ANSI Color 9',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-bright-red',
    default: '#fca5a5',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBrightGreen',
    label: 'ANSI Bright Green',
    description: 'Bright ANSI Color 10',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-bright-green',
    default: '#86efac',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBrightYellow',
    label: 'ANSI Bright Yellow',
    description: 'Bright ANSI Color 11',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-bright-yellow',
    default: '#fde047',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBrightBlue',
    label: 'ANSI Bright Blue',
    description: 'Bright ANSI Color 12',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-bright-blue',
    default: '#93c5fd',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBrightMagenta',
    label: 'ANSI Bright Magenta',
    description: 'Bright ANSI Color 13',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-bright-magenta',
    default: '#d8b4fe',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBrightCyan',
    label: 'ANSI Bright Cyan',
    description: 'Bright ANSI Color 14',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-bright-cyan',
    default: '#7dd3fc',
    scope: 'app',
  },
  {
    id: 'terminal.ansiBrightWhite',
    label: 'ANSI Bright White',
    description: 'Bright ANSI Color 15',
    category: 'terminal',
    subcategory: 'ANSI Colors',
    type: 'color',
    cssVar: '--terminal-ansi-bright-white',
    default: '#ffffff',
    scope: 'app',
  },

  // ==========================================
  // TERMINAL: App Log Colors
  // ==========================================
  {
    id: 'log.debug',
    label: 'Log Level: Debug',
    description: 'Color of [DEBUG] stream log entries in the terminal panel.',
    category: 'terminal',
    subcategory: 'App Log Colors',
    type: 'color',
    cssVar: '--log-debug',
    default: '#85818c',
    scope: 'app',
  },
  {
    id: 'log.info',
    label: 'Log Level: Info',
    description: 'Color of [INFO] stream log entries in the terminal panel.',
    category: 'terminal',
    subcategory: 'App Log Colors',
    type: 'color',
    cssVar: '--log-info',
    default: '#38bdf8',
    scope: 'app',
  },
  {
    id: 'log.success',
    label: 'Log Level: Success',
    description: 'Color of [SUCCESS] stream log entries in the terminal panel.',
    category: 'terminal',
    subcategory: 'App Log Colors',
    type: 'color',
    cssVar: '--log-success',
    default: '#4ade80',
    scope: 'app',
  },
  {
    id: 'log.warn',
    label: 'Log Level: Warn',
    description: 'Color of [WARN] stream log entries in the terminal panel.',
    category: 'terminal',
    subcategory: 'App Log Colors',
    type: 'color',
    cssVar: '--log-warn',
    default: '#facc15',
    scope: 'app',
  },
  {
    id: 'log.error',
    label: 'Log Level: Error',
    description: 'Color of [ERROR] stream log entries in the terminal panel.',
    category: 'terminal',
    subcategory: 'App Log Colors',
    type: 'color',
    cssVar: '--log-error',
    default: '#f87171',
    scope: 'app',
  },

  // ==========================================
  // GIT: Functional Settings
  // ==========================================
  {
    id: 'git.defaultBranch',
    label: 'Default Branch Name',
    description: 'Branch name initialized when creating new local repositories.',
    category: 'git',
    subcategory: 'Repository Defaults',
    type: 'text',
    default: 'main',
    scope: 'repo',
  },
  {
    id: 'git.autoFetchInterval',
    label: 'Background Auto-Fetch Interval',
    description: 'Periodically check remotes in background for new upstream commits (0 to disable).',
    category: 'git',
    subcategory: 'Sync & Remote Operations',
    type: 'number',
    default: 5,
    min: 0,
    max: 60,
    step: 1,
    unit: 'min',
    scope: 'app',
  },
  {
    id: 'git.pruneOnFetch',
    label: 'Prune Deleted Branches on Fetch',
    description: 'Automatically remove local tracking branches when deleted on remote (git fetch --prune).',
    category: 'git',
    subcategory: 'Sync & Remote Operations',
    type: 'boolean',
    default: true,
    scope: 'repo',
  },
  {
    id: 'git.confirmForcePush',
    label: 'Confirm Before Force Push',
    description: 'Display an interactive confirmation prompt before executing force push operations.',
    category: 'git',
    subcategory: 'Safety Checks',
    type: 'boolean',
    default: true,
    scope: 'app',
  },

  // ==========================================
  // ACCOUNTS & SECURITY
  // ==========================================
  {
    id: 'accounts.autoRefreshToken',
    label: 'Auto-Refresh OAuth Tokens',
    description: 'Silently refresh expiring GitLab/GitHub OAuth tokens before background polling.',
    category: 'accounts',
    subcategory: 'Authentication & Tokens',
    type: 'boolean',
    default: true,
    scope: 'app',
  },
  {
    id: 'accounts.confirmAccountRemoval',
    label: 'Confirm Account Removal',
    description: 'Prompt before revoking credentials and removing saved accounts from the registry.',
    category: 'accounts',
    subcategory: 'Authentication & Tokens',
    type: 'boolean',
    default: true,
    scope: 'app',
  },
  {
    id: 'accounts.logRetentionDays',
    label: 'Audit Log Retention',
    description: 'Maximum number of days to retain persisted log history before automatic rotation.',
    category: 'accounts',
    subcategory: 'Log Storage',
    type: 'number',
    default: 30,
    min: 7,
    max: 365,
    step: 7,
    unit: 'days',
    scope: 'app',
  },

  // ==========================================
  // NOTIFICATIONS
  // ==========================================
  {
    id: 'notifications.enablePushSuccess',
    label: 'Notify on Successful Push',
    description: 'Send a desktop notification whenever a branch push operation succeeds.',
    category: 'notifications',
    subcategory: 'System Alerts',
    type: 'boolean',
    default: true,
    scope: 'app',
  },
  {
    id: 'notifications.enableFetchNewCommits',
    label: 'Notify on New Remote Commits',
    description: 'Send a toast notification when background fetch detects new commits on current branch.',
    category: 'notifications',
    subcategory: 'System Alerts',
    type: 'boolean',
    default: true,
    scope: 'app',
  },
  {
    id: 'notifications.enableConflictAlert',
    label: 'Notify on Merge Conflicts',
    description: 'Alert when a rebase, merge, or cherry-pick hits a conflict requiring manual resolution.',
    category: 'notifications',
    subcategory: 'System Alerts',
    type: 'boolean',
    default: true,
    scope: 'app',
  },

  // ==========================================
  // ADVANCED
  // ==========================================
  {
    id: 'advanced.logVerbosity',
    label: 'Application Log Verbosity',
    description: 'Minimum logging level recorded to disk and displayed in the application log view.',
    category: 'advanced',
    subcategory: 'Diagnostics & Performance',
    type: 'select',
    options: [
      { label: 'Debug (All events)', value: 'debug' },
      { label: 'Info (Standard)', value: 'info' },
      { label: 'Warning (Warnings & errors only)', value: 'warn' },
      { label: 'Error (Errors only)', value: 'error' },
    ],
    default: 'info',
    scope: 'app',
  },
  {
    id: 'advanced.terminalScrollback',
    label: 'Terminal Scrollback Line Buffer',
    description: 'Maximum number of terminal output lines retained in memory.',
    category: 'advanced',
    subcategory: 'Diagnostics & Performance',
    type: 'number',
    default: 5000,
    min: 1000,
    max: 50000,
    step: 1000,
    unit: 'lines',
    scope: 'app',
  },
  {
    id: 'advanced.hardwareAcceleration',
    label: 'Hardware GPU Canvas Acceleration',
    description: 'Use WebGL canvas acceleration for terminal rendering where supported.',
    category: 'advanced',
    subcategory: 'Diagnostics & Performance',
    type: 'boolean',
    default: true,
    scope: 'app',
  },
];
