#[macro_export]
macro_rules! log_info {
    ($category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Info,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Info,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Info,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Info,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Info,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Info,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Info,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Info,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
}

#[macro_export]
macro_rules! log_success {
    ($category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Success,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Success,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Success,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Success,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Success,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Success,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Success,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Success,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
}

#[macro_export]
macro_rules! log_warn {
    ($category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Warn,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Warn,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Warn,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Warn,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Warn,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Warn,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Warn,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Warn,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
}

#[macro_export]
macro_rules! log_error {
    ($category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Error,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Error,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Error,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Error,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Error,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Error,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Error,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Error,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
}

#[macro_export]
macro_rules! log_debug {
    ($category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Debug,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Debug,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Debug,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            None,
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Debug,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Debug,
                $category,
                $msg,
                None,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Debug,
                $category,
                $msg,
                $repo,
                None,
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Debug,
                $category,
                $msg,
                None,
                Some($meta),
            ),
        );
    };
    ($app:expr, $category:expr, $msg:expr; repo_id: $repo:expr, meta: $meta:expr) => {
        $crate::core::logging::bus::log(
            Some($app),
            $crate::core::logging::model::LogEntry::new(
                $crate::core::logging::model::LogLevel::Debug,
                $category,
                $msg,
                $repo,
                Some($meta),
            ),
        );
    };
}
